### ISSUE TITLE
The Sign in process fails.

### ISSUE THREAD

**Issue by mfocht** [rocky4546/script.xmltv.tvheadend#1]
The redesign of the zap2it website means that this link (http://tvschedule.zap2it.com/tvlistings/ZCLogin.do) errors out.  This means that the script always fails.  It appears to work if you comment out the lines that do the checking, (assuming you enter the correct password,) but I'm not sure.  Guess I'll see in a day or so here.

**Comment by sabre6** [comment]
You may need to update zap2xml.pl, as the author has fixed for the new website.

**Comment by mfocht** [comment]
Yep, it's all the way up to date.  I just set this up on this machine yesterday, so I got the fixed version. If I run the command manually it works.  The issue I have is on line 173 of the install.sh script.  It tests the login to make sure that it is correct, but it always returns a 404, even when the password is correct.

**Comment by sabre6** [comment]
oh, ok. I did run into issues with the install.sh script, so did the manual install. Eventually I was able to make it work. And after updating zap2xml.pl, it again works with the same setup i had. Sorry i cant help more.

**Comment by rocky4546** [comment]
Working through updates now.  First, make sure you have the latest zap2xml.pl file from http://zap2xml.awardspace.info/
It was updated on 1/8 with the changes needed.  Next, the site claims you will need to remove the cache before it will work.  You should see a cache folder.  Delete everything out of that.  Lastly, it states that you no longer need the "-D" option.  I am checking that now to see if that will get all the data.  I will check on the other issues you are mentioning and get back to you.

**Comment by mfocht** [comment]
Thanks.  I appreciate your help.

**Comment by rocky4546** [comment]
Not releasing anything yet, but the install.sh has been updated to support the new interface which is now fully JSON based.  I figured out what is needed to get TVHeadend back up and running.  To do that, you need to delete all entries in the Configuration => Channel/EPG => EPG Grabber Channels.  This is because zap2it has totally new IDs.  After getting a new xmltv.xml file, import it by clicking Configuration => Channel/EPG => EPG Grabber => Re-run Internal EPG Grabbers.
This will repopulate the EPG Grabber Channels list.  Next, go through each of the items listed and assign a Channel in the Channels column.  This will connect the EPG to the xmltv.xml file.
Next, reload the xmltv.xml file again by clicking the Re-run Internal EPG Grabbers.  At this point, TVHeadend should be updated with the new EPG data.  Kodi will then resync based on the resync times in KODI.  Still going through the details and testing, but all looks good.  Remember that the -D option is no longer needed to generate the xmltv.xml file.

**Comment by rocky4546** [comment]
All files have been updated and are released.  Also found an issue with zap2xml.pl file downloaded remotely.  The developer for that file has made the updates, so I recommend pulling down the new file.  Today's updates include a workaround for an issue I found with zap2xml.pl in that it does not always refresh the current day's data.  The zap2xml.sh now has lines to remove those cached files so any updates to today's guide is refreshed.  Lastly, I found more information on genre categories between zap2it, TVHeadend and Kodi.  I have added a new file called strings.po.  If you go to Kodi => Settings => Interface => Regional and change Language from "English" to "English (US)" the structure in .kodi/addons/resources* will appear.  You can overwrite the strings.po file which will sync Kodi with TVHeadend genres.
